# 1. Node image
FROM node:18-alpine

# 2. Working directory
WORKDIR /app

# 3. Copy package files
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Copy all project
COPY . .

# 6. Build Next.js
RUN npm run build

# 7. Expose port
EXPOSE 3000

# 8. Start app
CMD ["npm", "start"]
